#### Data Structures

In [1]:
# Numpy : multi-dim arrays and stats methods

import numpy as np

arr = np.array([4,5,6,7,10])

In [2]:
arr.ndim 

1

In [3]:
arr2 = np.array([
    [2,3,4],
    [2,1,4]
])

In [4]:
arr2.ndim

2

In [5]:
arr2.shape

(2, 3)

Indexing and Slicing

In [6]:
arr[0]

4

In [7]:
arr[-1]

10

In [8]:
arr[:2]

array([4, 5])

In [10]:
arr2[0,1]

3

In [11]:
arr2[0]

array([2, 3, 4])

In [12]:
arr2[:,2]

array([4, 4])

In [13]:
arr

array([ 4,  5,  6,  7, 10])

In [14]:
arr.mean()

6.4

In [15]:
arr.std()

2.0591260281974

In [16]:
np.median(arr)

6.0

In [17]:
np.mean(arr)

6.4

In [19]:
np.std(arr)

2.0591260281974

##### Pandas

In [20]:
# Series
# DataFrame

In [1]:
# Series
import pandas as pd

animals = pd.Series(['cat', 'dog', 'hen'])

C:\Users\aaginam\AppData\Local\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [22]:
animals

0    cat
1    dog
2    hen
dtype: object

In [23]:
animals = pd.Series(['cat', 'dog', 'hen'], index=['a', 'b', 'c'])

In [24]:
animals

a    cat
b    dog
c    hen
dtype: object

In [28]:
animals['a':'b']

a    cat
b    dog
dtype: object

In [29]:
student_scores = {
    'names' : ['Ben', 'James', 'Charles'],
    'scores':[40, 50, 45]
}

In [31]:
data = pd.DataFrame(student_scores)

In [32]:
data

names  scores
0      Ben      40
1    James      50
2  Charles      45

In [2]:
df = pd.read_csv('cancer dataset.csv', sep=';')

In [3]:
df

clump  ucellsize  ucellshape  mgadhesion  sepics  bnuclei  bchromatin  \
0        4          1           1           1       2        3           1   
1        1          5           8           6       5        8           7   
2        3          2           2           3       2        1           1   
3        3          1           1           3       8        1           5   
4       10          4           6           1       2       10           5   
..     ...        ...         ...         ...     ...      ...         ...   
295      4          1           1           1       2        1           3   
296      5          1           1           4       2        1           3   
297      5          1           1           1       2        1           2   
298      5          7           9           8       6       10           8   
299      5          1           1           1       2        1           2   

     normnucl  mitoses     classe  
0           1        1     begnin  
1          10        1  malignant  
2           1        1     begnin  
3           8        1     begnin  
4           3        1  malignant  
..        ...      ...        ...  
295         1        1     begnin  
296         1        1     begnin  
297         1        1     begnin  
298        10        1  malignant  
299         1        1     begnin  

[300 rows x 10 columns]

In [4]:
df['clump size'] = df['clump'] * df['ucellsize']

In [5]:
df.head()

clump  ucellsize  ucellshape  mgadhesion  sepics  bnuclei  bchromatin  \
0      4          1           1           1       2        3           1   
1      1          5           8           6       5        8           7   
2      3          2           2           3       2        1           1   
3      3          1           1           3       8        1           5   
4     10          4           6           1       2       10           5   

   normnucl  mitoses     classe  clump size  
0         1        1     begnin           4  
1        10        1  malignant           5  
2         1        1     begnin           6  
3         8        1     begnin           3  
4         3        1  malignant          40

In [8]:
#pandas vectorized method -HOF

def categorize_cell_shape(cell_shape):
    if cell_shape <= 5:
        return 'Low'
    elif cell_shape >5 and cell_shape <=10:
        return 'medium'
    else:
        return 'high'

df['Cell shape category'] = df['ucellshape'].apply(categorize_cell_shape)

In [9]:
df.head()

clump  ucellsize  ucellshape  mgadhesion  sepics  bnuclei  bchromatin  \
0      4          1           1           1       2        3           1   
1      1          5           8           6       5        8           7   
2      3          2           2           3       2        1           1   
3      3          1           1           3       8        1           5   
4     10          4           6           1       2       10           5   

   normnucl  mitoses     classe  clump size Cell shape category  
0         1        1     begnin           4                 Low  
1        10        1  malignant           5              medium  
2         1        1     begnin           6                 Low  
3         8        1     begnin           3                 Low  
4         3        1  malignant          40              medium